### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [vwochnik/jekyll-language-plugin#16]
Hello all,

I am sorry but I work with the last version of Jekyll and I still got error on a build:

`/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in`rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-language-plugin'. (Bundler::GemRequireError)
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:39:in `require_from_bundler'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.3/bin/jekyll:13:in`<top (required)>'
    from /usr/local/bin/jekyll:22:in `load'
    from /usr/local/bin/jekyll:22:in`<main>'`

I read the "Getting Started" in a wiki page and I copy/past this code in my Gemfile :
`gems:
- jekyll-language-plugin`
- add this :
  `language_data: data.lang.fr
  language_includes_dir: _i18n`

Has you see, I would like a translate a date in French from the Liquid Markup. I do not have (and do not need yet) a folder called __i18n_. I just tried create this folder with _fr_ subfolder but still same.

Some help will be appreciated, thanks.

**Comment by vwochnik** [comment]
The current build of the `jekyll-language-plugin` requires `jekyll` version `3.1.2`, not `3.0.3`.

Here is an improved [`Gemfile`](https://github.com/vwochnik/jekyll-language-plugin/blob/master/example/Gemfile). You can also check out the example site completely to get an idea on how the plugin is working.

**Comment by ghost** [comment]
Thanks, but trying to resolved this problem I get another, nothing works now (I got two version of Jekyll, so I deleted both and reinstall the one).

When I launch the gulp command, the destination folder stay empty.

And I have this message log:
`bundler: command not found: jekyll
Install missing gem executables with "bundle install"`

Problem is when I use bundle install, everything looks ok.

My OS is El Capitan, so I tried to install Jekyll by this:

`sudo gem install -n /Library/Ruby/Gems/2.0.0/gems/ jekyll`

But still same, it's like hole where I cannot get out. Do you have some idea please ?

**Comment by vwochnik** [comment]
No, this doesn't work this way. Bundler is used for managing project-related dependencies. This means that you have your system- and user-wide ruby gems directory as you probably know.

Then, you have Bundler. It is essentially like `npm` or `bower` if you are coming from there. Bundler installs gems to your local project directory to avoid just the scenario you have described. This allows you to use two versions of `jekyll` in parallel without interference.

I'd suggest you start out by downloading the [`example`](https://github.com/vwochnik/jekyll-language-plugin/tree/master/example) directory of this project. I'm also using El Capitan, this works no problem. Just switch to the example directory and type `bundle install`. This will load all dependencies declared in the `Gemfile` and their dependencies as well.

Then if you want to execute the `jekyll` command, because you are using Bundler, you always have to prepend `bundle exec` and Bundler routes the command to the `jekyll` executable. Just try `bundle exec jekyll serve` and go to `http://localhost:4000/`.

**Comment by git-no** [comment]
Having trouble with OS X El Capitan?
Maybe this helps: [Jekyll & Mac OS X 10.11](https://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011)
